services:
  - type: worker
    name: xauusd-stochastic-bot
    env: python
    plan: free
    pythonVersion: 3.12.3
    buildCommand: ""
    startCommand: python background_bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7308283803:AAHm3CmrIlpGoehyAhX9xgJdAzTn_bZcJcU
      - key: CHAT_ID
        value: 6748992445
      - key: API_KEY
        value: 78ade9c6b5de4093951a1e99afa96f50
